describe('chocoblast', () => {
    it('ok', () => {
        cy.visit('https://127.0.0.1:8000/login')
        cy.get('#inputEmail').type("mathieu.mith@laposte.net")
        cy.get('#inputPassword').type("Azertyuio1234")
        cy.get('.btn').click()
        cy.visit('https://127.0.0.1:8000/chocoblast/add')
        cy.wait(2000)
        cy.get('#chocoblast_title').type("new choco cypress1")
        cy.get('#chocoblast_createAt').type('2024-04-08')
        //cy.get('#chocoblast_target-ts-label').click()
        cy.get('#chocoblast_target').select(1, { force: true })
        cy.get('#chocoblast_ajouter').click()
        cy.wait(2000)
        cy.get('p.alert').should('contain', "le chocoblast a ete ajoute")
    })
    it('doublon', () => {
        cy.visit('https://127.0.0.1:8000/login')
        cy.get('#inputEmail').type("mathieu.mith@laposte.net")
        cy.get('#inputPassword').type("Azertyuio1234")
        cy.get('.btn').click()
        cy.visit('https://127.0.0.1:8000/chocoblast/add')
        cy.get('#chocoblast_title').type("new choco cypress1")
        cy.get('#chocoblast_createAt').type('2024-04-08')
        //cy.get('#chocoblast_target-ts-label').click()
        cy.get('#chocoblast_target').select(1, { force: true })
        cy.get('#chocoblast_ajouter').click()
        cy.wait(2000)
        cy.get('p.alert').should('contain', "Le chocoblast existe deja")
    })
})